pub const ARENA_WIDTH: f32 = 320.;
pub const ARENA_HEIGHT: f32 = 480.;

pub const SHIP_SPRITE_WIDTH: f32 = 16.;
pub const SHIP_SPRITE_HEIGHT: f32 = 24.;

pub const ENEMY_BIG_SPRITE_WIDTH: f32 = 32.;
pub const ENEMY_BIG_SPRITE_HEIGHT: f32 = 32.;

pub const ENEMY_MEDIUM_SPRITE_WIDTH: f32 = 32.;
pub const ENEMY_MEDIUM_SPRITE_HEIGHT: f32 = 16.;

pub const ENEMY_SMALL_SPRITE_WIDTH: f32 = 16.;
pub const ENEMY_SMALL_SPRITE_HEIGHT: f32 = 16.;
