pub const ARENA_WIDTH: f32 = 600.;
pub const ARENA_HEIGHT: f32 = 800.;
pub const SPRITE_UNIFORM_SCALING_FACTOR: f32 = 4.;

pub const PLAYER_SPRITE_WIDTH: f32 = 16.;
pub const PLAYER_SPRITE_HEIGHT: f32 = 24.;

pub const ENEMY_BIG_SPRITE_WIDTH: f32 = 32.;
pub const ENEMY_BIG_SPRITE_HEIGHT: f32 = 32.;

pub const ENEMY_MEDIUM_SPRITE_WIDTH: f32 = 32.;
pub const ENEMY_MEDIUM_SPRITE_HEIGHT: f32 = 16.;

pub const ENEMY_SMALL_SPRITE_WIDTH: f32 = 16.;
pub const ENEMY_SMALL_SPRITE_HEIGHT: f32 = 16.;
